// Chinese help for every canonical upstream component. Types and options stay unchanged.
const help = (label, description, requirements, category) => ({ label, description, requirements, category });
const general = (label, description, requirements = '使用公共数据服务；按原版参数文档配置。') => help(label, description, requirements, '生活与资讯');
const service = (label, description, requirements) => help(label, description, requirements, '自托管服务');
const monitor = (label, description) => help(label, description, '需要运行 Glances Web API，并填写其地址；云端代理无法直接访问家庭内网，可按部署环境使用浏览器直连或独立后端。', '主机监控');
const netdata = (label, description) => help(label, description, '需要运行 Netdata 并提供可访问的 API 地址。', '主机监控');
const nextcloud = (label, description) => service(label, description, '需要 Nextcloud 地址和相应账号／应用密码；部分管理数据需要管理员权限。');
const adguard = (label, description) => service(label, description, '需要 AdGuard Home 地址及登录凭据；不是安装此组件就自动获得过滤服务。');
const pihole = (label, description, version) => service(label, description, `需要 Pi-hole ${version} 的 API 地址及对应认证参数；v5 与 v6 接口不可混用。`);
export const WIDGET_HELP = {
  clock: general('时钟', '显示时间、日期和地点，可同时添加不同时区。', '无需外部 API；默认跟随设备，或设置 timeZone、format。'),
  weather: general('实况天气', '显示当地温度、天气、风速和湿度，支持城市或精确经纬度。', '使用 OpenWeather；本总站默认读取 CF Secret OPENWEATHER_API_KEY，保留一位小数。'),
  'weather-forecast': general('天气预报', '按天展示未来天气、温度和详细情况。', '需要 OpenWeather API Key 与支持该预报接口的套餐；实况天气密钥不代表拥有预报权限。'),
  image: help('图片', '显示图片、壁纸或监控图表快照，可设置刷新间隔。', '填写 imagePath；远程图片由浏览器加载。', '自定义与嵌入'),
  iframe: help('嵌入网页', '把网页或公开状态页嵌入小组件。', '填写 url；对方必须允许 iframe 嵌入，HTTPS 页面应嵌入 HTTPS 地址。', '自定义与嵌入'),
  embed: help('HTML 内容', '显示自定义 HTML 内容，例如公告和格式化文本。', '填写 html；显示内容经过安全处理，不用于执行任意网页脚本。', '自定义与嵌入'),
  'custom-api': help('自定义 API', '从 JSON 接口提取数值、列表或图表数据。', '填写 endpoint、取值字段等参数；需要密钥时使用占位符与代理。', '自定义与嵌入'),
  'custom-list': help('自定义数据列表', '按自定义标签和格式展示数据列表。', '按原版列表参数配置数据源与字段。', '自定义与嵌入'),
  'custom-search': help('自定义搜索', '提供可直接提交关键词的搜索入口。', '配置搜索服务与 URL 模板。', '自定义与嵌入'),
  calendar: general('日历与日程', '显示日历以及订阅日历中的事件。', '日历可直接显示；读取事件需配置可访问的 ICS 订阅地址。'),
  'rss-feed': general('RSS 订阅', '汇总 RSS 或 Atom 新闻及更新。', '填写 rssUrl；可本地解析，或使用 rss2json 服务及可选密钥。'),
  'public-ip': general('公网 IP', '显示当前网络的公网地址和相关信息。', '使用公共 IP 查询接口；显示的是发出查询的网络，代理会影响结果。'),
  'blacklist-check': general('IP 黑名单检查', '检查公网 IP 是否出现在反垃圾邮件黑名单。', '按原版配置目标 IP；结果用于参考，不能代表网站可用性。'),
  'domain-monitor': general('域名注册与到期', '查看注册状态、到期倒计时、注册商和域名服务器。', '填写要查询的域名及组件要求的数据服务参数。'),
  'code-stats': general('编程统计', '显示 Code::Stats 用户的编码经验与活动。', '填写 Code::Stats 用户名；自建实例可修改 hostname。'),
  'mullvad-status': general('Mullvad 连接状态', '显示当前网络是否通过 Mullvad VPN 连接。', '使用 Mullvad 查询服务；代理查询会反映代理所在网络。'),
  addy: service('邮箱别名统计', '显示 addy.io 邮箱别名、转发等统计。', '需要 addy.io／AnonAddy API Token，自建服务可配置地址。'),
  'cve-vulnerabilities': general('安全漏洞资讯', '显示 NVD 发布的 CVE 漏洞及风险信息。', '支持筛选参数及可选 NVD API Key；注意接口限流。'),
  'exchange-rates': general('货币汇率', '显示选定基础货币与其他货币的汇率。', '需要汇率服务 API Key，并设置货币代码；不是银行成交报价。'),
  'public-holidays': general('公共假日', '展示指定国家的法定假日。', '配置国家代码等参数。'),
  'covid-stats': general('疫情统计', '展示数据服务提供的疫情统计。', '依赖外部历史统计服务，其更新频率与接口可用性由提供方决定。'),
  'sports-scores': general('体育比分', '显示球队或联赛近期赛程与结果。', '设置球队／联赛 ID；数据来自 TheSportsDB，部分请求可能需要密钥。'),
  'live-tennis': general('网球赛况', '显示网球比赛和比分信息。', '需要 Live Tennis API 的 apiKey。'),
  'news-headlines': general('新闻头条', '展示新闻来源提供的头条和摘要。', '按原版配置新闻 API Key 与筛选条件。'),
  'tfl-status': general('伦敦交通状态', '显示 TfL 公共交通线路运行情况。', '使用伦敦 TfL 数据，可配置线路筛选。'),
  'stock-price-chart': general('股票价格图表', '展示指定证券的历史价格变化。', '需要股票代码与 Alpha Vantage API Key；数据可能延迟并受限流影响。'),
  'eth-gas-prices': general('以太坊 Gas 费用', '显示以太坊网络交易费用参考。', '依赖 Gas 数据服务；仅供查看，不发起交易。'),
  joke: general('每日笑话', '展示公共服务提供的随机笑话。', '依赖外部笑话接口，无需部署自建服务。'),
  chucknorris: general('Chuck Norris 趣味语录', '展示 Chuck Norris 风格的随机趣味语录。', '依赖公共语录 API。'),
  'xkcd-comic': general('XKCD 漫画', '显示 XKCD 漫画和标题。', '依赖 XKCD 数据接口，跨域时使用代理。'),
  'flight-data': general('航班信息', '展示航班、航空公司等查询结果。', '需要 RapidAPI 对应航班服务的 API Key 和查询参数。'),
  apod: general('NASA 每日天文图', '显示 NASA APOD 每日天文图片或视频及介绍。', '默认使用公共 APOD 接口；可选配置自建代理的 hostname。'),
  'github-trending-repos': general('GitHub 热门项目', '展示热门开源仓库及项目简介。', '可设置语言、时间范围等筛选；依赖外部趋势数据接口。'),
  'github-profile-stats': general('GitHub 用户统计', '显示用户仓库、关注者等资料。', '填写 GitHub 用户名；注意公共 API 的请求限额。'),
  'hackernews-trending': general('Hacker News 热门', '展示 Hacker News 热门讨论和链接。', '使用公共新闻接口，可设置条目数量。'),
  'health-checks': service('定时任务健康检查', '查看 Healthchecks 中任务的心跳、运行与超时状态。', '需要 Healthchecks 项目的 API Key；任务需先向该服务报告心跳。'),
  mvg: general('慕尼黑交通出发信息', '显示 MVG 指定站点的出发班次。', '设置站点和筛选参数，数据依赖 MVG 服务。'),
  'mvg-connection': general('慕尼黑交通换乘', '显示 MVG 起点与终点之间的路线连接。', '配置起终点与路线参数。'),
  'rescue-time': general('时间使用统计', '展示 RescueTime 记录的活动和时间分配。', '需要 RescueTime API Key；需先使用其客户端采集数据。'),
  'minecraft-status': general('Minecraft 服务器状态', '显示 Minecraft 服务的在线人数等信息。', '配置服务器地址及可选端口；使用状态查询 API。'),
  'crypto-watch-list': general('加密货币行情列表', '查看选定币种价格和涨跌。', '配置币种及计价货币；依赖行情 API，不发起交易。'),
  'crypto-price-chart': general('加密货币历史价格', '展示币种价格变化图表。', '配置币种和时间范围；依赖行情数据服务。'),
  'wallet-balance': general('公开钱包余额', '查询公开链地址的余额和交易。', '填写币种与公开地址；无需也不应填写钱包私钥。'),
  'system-info': help('后端主机信息', '显示运行 Dashy 后端的主机系统信息。', 'CF Workers 不提供真实主机指标；需连接支持 system-info 的独立 Dashy 后端。', '主机监控'),
  'gl-alerts': monitor('Glances 资源告警', '展示主机资源超出阈值的告警。'),
  'gl-current-cores': monitor('Glances 各核心 CPU', '分别显示 CPU 各核心的当前使用率。'),
  'gl-current-cpu': monitor('Glances CPU 仪表', '通过仪表显示当前 CPU 使用率。'),
  'gl-cpu-speedometer': monitor('Glances CPU 指针表', '通过速度表样式显示 CPU 使用率。'),
  'gl-cpu-history': monitor('Glances CPU 历史', '显示 CPU 使用率随时间变化。'),
  'gl-disk-io': monitor('Glances 磁盘读写', '展示磁盘读写吞吐量。'),
  'gl-disk-space': monitor('Glances 磁盘空间', '查看各磁盘容量与占用情况。'),
  'gl-ip-address': monitor('Glances 主机 IP', '显示被监控主机的公网和内网地址。'),
  'gl-load-history': monitor('Glances 负载历史', '展示主机系统负载变化。'),
  'gl-current-mem': monitor('Glances 内存仪表', '显示当前内存使用情况。'),
  'gl-mem-speedometer': monitor('Glances 内存指针表', '通过速度表样式显示内存占用。'),
  'gl-mem-history': monitor('Glances 内存历史', '展示内存使用随时间变化。'),
  'gl-network-interfaces': monitor('Glances 网络接口', '显示网络接口及其信息。'),
  'gl-network-traffic': monitor('Glances 网络流量', '显示各接口收发数据速率。'),
  'gl-system-load': monitor('Glances 系统负载', '展示当前系统负载指标。'),
  'gl-uptime': monitor('Glances 运行时长', '显示被监控主机连续运行的时间。'),
  'gl-cpu-temp': monitor('Glances CPU 温度', '展示主机温度传感器读数。'),
  'gl-gpu': monitor('Glances GPU 状态', '显示 GPU 使用、显存等可用指标。'),
  'gl-compact-metrics': monitor('Glances 紧凑监控', '在一个组件内汇总 CPU、内存等主要指标。'),
  'nd-cpu-history': netdata('Netdata CPU 历史', '显示 Netdata 采集的 CPU 使用曲线。'),
  'nd-load-history': netdata('Netdata 负载历史', '显示 Netdata 采集的系统负载曲线。'),
  'nd-ram-history': netdata('Netdata 内存历史', '显示 Netdata 采集的内存使用曲线。'),
  'pi-hole-stats': pihole('Pi-hole v5 统计', '汇总 DNS 查询和拦截数量。', 'v5'),
  'pi-hole-stats-v6': pihole('Pi-hole v6 统计', '汇总 DNS 查询和拦截数量。', 'v6'),
  'pi-hole-top-queries': pihole('Pi-hole v5 热门查询', '展示最常查询或拦截的域名。', 'v5'),
  'pi-hole-top-queries-v6': pihole('Pi-hole v6 热门查询', '展示最常查询或拦截的域名。', 'v6'),
  'pi-hole-traffic': pihole('Pi-hole v5 流量', '展示近期 DNS 查询与拦截趋势。', 'v5'),
  'pi-hole-traffic-v6': pihole('Pi-hole v6 流量', '展示近期 DNS 查询与拦截趋势。', 'v6'),
  'adguard-dns-info': adguard('AdGuard DNS 信息', '查看 DNS 服务的运行信息。'),
  'adguard-filter-status': adguard('AdGuard 过滤规则', '查看过滤订阅与启用状态。'),
  'adguard-stats': adguard('AdGuard 拦截统计', '查看 DNS 查询与过滤统计。'),
  'adguard-top-domains': adguard('AdGuard 热门域名', '展示最常查询和拦截的域名。'),
  'nextcloud-user': nextcloud('Nextcloud 用户', '显示当前用户的资料和存储信息。'),
  'nextcloud-user-status': nextcloud('Nextcloud 用户状态', '显示用户在线及自定义状态。'),
  'nextcloud-notifications': nextcloud('Nextcloud 通知', '显示用户收到的通知。'),
  'nextcloud-system': nextcloud('Nextcloud 系统', '查看实例系统信息。'),
  'nextcloud-stats': nextcloud('Nextcloud 统计', '汇总实例用户、文件等统计。'),
  'nextcloud-php-opcache': nextcloud('Nextcloud PHP 缓存', '查看 PHP OPcache 缓存与使用情况。'),
  'ntfy-stream': service('ntfy 通知流', '持续显示 ntfy 主题收到的通知。', '配置服务器和 topic；私有主题需要认证。'),
  'proxmox-lists': service('Proxmox 虚拟机列表', '显示节点、虚拟机和容器状态。', '需要 Proxmox API 地址与有读取权限的 Token。'),
  sabnzbd: service('SABnzbd 下载', '展示下载队列和任务状态。', '需要 SABnzbd 地址及 API Key。'),
  'gluetun-status': service('Gluetun VPN 信息', '查看 Gluetun VPN 容器的连接信息。', '需要启用并可访问的 Gluetun 控制接口。'),
  'drone-ci': service('Drone CI 构建', '展示项目构建状态。', '需要 Drone 地址、项目和访问 Token。'),
  filebrowser: service('Filebrowser 文件', '展示文件浏览器中的文件与目录。', '需要 Filebrowser 地址和登录参数。'),
  linkding: service('Linkding 书签', '显示保存的书签和标签。', '需要 Linkding 地址和 API Token。'),
  'uptime-kuma-status-page': service('Uptime Kuma 公开状态页', '汇总公开状态页中的服务健康情况。', '填写 Kuma 地址和状态页 slug；状态页需先创建并公开。'),
  'uptime-kuma': service('Uptime Kuma 监控', '显示 Kuma 监控项目状态。', '需要 Kuma 服务地址及对应认证参数。'),
  'stat-ping': service('Statping 服务状态', '显示 Statping 的服务健康与检查结果。', '需要已运行的 Statping 实例及其 API 地址。'),
  'synology-download': service('群晖下载任务', '查看 Synology Download Station 下载状态。', '需要群晖 DSM 地址及相应账号权限。'),
  trmm: service('Tactical RMM 设备管理', '显示设备与远程监控统计。', '需要 Tactical RMM API 地址及访问密钥。'),
};
